import React, { createContext, useContext, useEffect, useState, useRef, type ReactNode } from 'react';
import { View, Text, TouchableOpacity, StyleSheet, ActivityIndicator, Image, Platform } from 'react-native';
import { supabase } from '@/services/supabase';
import { Sheet } from '@/components/ui/sheet';
import Icon from 'react-native-remix-icon';
import { colors, typography } from '@/constants/theme';
import * as WebBrowser from 'expo-web-browser';
import * as Linking from 'expo-linking';
import type { Session, User } from '@supabase/supabase-js';

WebBrowser.maybeCompleteAuthSession();

type AuthContextValue = {
  user: User | null;
  session: Session | null;
  loading: boolean;
  showGoogleSignIn: (onSuccess?: () => void) => void;
  signOut: () => Promise<void>;
  authSheetVisible: boolean;
  setAuthSheetVisible: (visible: boolean) => void;
  authBusy: boolean;
  errorMessage: string | null;
  handleGoogleSignIn: () => Promise<void>;
  handleGuestSignIn: () => Promise<void>;
};

const AuthContext = createContext<AuthContextValue>({
  user: null,
  session: null,
  loading: true,
  showGoogleSignIn: () => {},
  signOut: async () => {},
  authSheetVisible: false,
  setAuthSheetVisible: () => {},
  authBusy: false,
  errorMessage: null,
  handleGoogleSignIn: async () => {},
  handleGuestSignIn: async () => {},
});

export function useAuth() {
  return useContext(AuthContext);
}

export function AuthProvider({ children }: { children: ReactNode }) {
  const [user, setUser] = useState<User | null>(null);
  const [session, setSession] = useState<Session | null>(null);
  const [loading, setLoading] = useState(true);
  const [authSheetVisible, setAuthSheetVisible] = useState(false);
  const [authBusy, setAuthBusy] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const pendingCallbackRef = useRef<(() => void) | null>(null);

  // Initialize session and auth state listener
  useEffect(() => {
    supabase.auth.getSession().then(({ data }) => {
      setSession(data.session);
      setUser(data.session?.user ?? null);
      setLoading(false);
    });

    const { data: listener } = supabase.auth.onAuthStateChange((_event, newSession) => {
      setSession(newSession);
      setUser(newSession?.user ?? null);
      setLoading(false);

      if (newSession?.user) {
        if (pendingCallbackRef.current) {
          const cb = pendingCallbackRef.current;
          pendingCallbackRef.current = null;
          setTimeout(() => {
            cb();
          }, 400);
        }
        setAuthSheetVisible(false);
      }
    });

    return () => {
      listener.subscription.unsubscribe();
    };
  }, []);

  const showGoogleSignIn = (onSuccess?: () => void) => {
    if (onSuccess) {
      pendingCallbackRef.current = onSuccess;
    } else {
      pendingCallbackRef.current = null;
    }
    setErrorMessage(null);
    setAuthSheetVisible(true);
  };

  const handleGoogleSignIn = async () => {
    setAuthBusy(true);
    setErrorMessage(null);
    try {
      const redirectTo = Linking.createURL('/auth/callback');
      console.log("[Auth] Google Sign-In redirect URL generated by Expo:", redirectTo);
      const { data, error } = await supabase.auth.signInWithOAuth({
        provider: 'google',
        options: {
          redirectTo,
          skipBrowserRedirect: true,
        },
      });

      if (error) throw error;
      if (!data?.url) throw new Error("No URL returned from Supabase OAuth.");

      const result = await WebBrowser.openAuthSessionAsync(data.url, redirectTo);
      
      if (result.type === 'success') {
        const { url } = result;
        const parsed = Linking.parse(url);
        const { access_token, refresh_token } = parsed.queryParams || {};

        if (access_token && refresh_token) {
          const { error: sessionError } = await supabase.auth.setSession({
            access_token: String(access_token),
            refresh_token: String(refresh_token),
          });
          if (sessionError) throw sessionError;
        }
      }
    } catch (err: any) {
      console.error("Google Sign-In Error:", err);
      setErrorMessage(err.message || "Failed to sign in with Google.");
    } finally {
      setAuthBusy(false);
    }
  };

  const handleGuestSignIn = async () => {
    setAuthBusy(true);
    setErrorMessage(null);
    try {
      const { data, error } = await supabase.auth.signInAnonymously();
      if (error) throw error;
      if (!data?.user) throw new Error("Anonymous login failed.");
    } catch (err: any) {
      console.error("Guest Login Error:", err);
      setErrorMessage(err.message || "Failed to sign in as Guest.");
    } finally {
      setAuthBusy(false);
    }
  };

  const signOut = async () => {
    setLoading(true);
    try {
      await supabase.auth.signOut();
    } catch (err) {
      console.error("Sign Out Error:", err);
    } finally {
      setUser(null);
      setSession(null);
      setLoading(false);
    }
  };

  return (
    <AuthContext.Provider
      value={{
        user,
        session,
        loading,
        showGoogleSignIn,
        signOut,
        authSheetVisible,
        setAuthSheetVisible,
        authBusy,
        errorMessage,
        handleGoogleSignIn,
        handleGuestSignIn
      }}
    >
      {children}
    </AuthContext.Provider>
  );
}

const styles = StyleSheet.create({
  sheetHeader: {
    alignItems: 'center',
    paddingVertical: 12,
  },
  appIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 18,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 4,
  },
  sheetTitle: {
    ...typography.headline,
    color: '#fff',
    fontSize: 22,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 8,
  },
  sheetSubtitle: {
    ...typography.body,
    color: 'rgba(255,255,255,0.6)',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    paddingHorizontal: 16,
  },
  errorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,59,48,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255,59,48,0.2)',
    padding: 12,
    borderRadius: 12,
    gap: 8,
    marginHorizontal: 16,
    marginTop: 8,
  },
  errorText: {
    color: colors.danger,
    fontSize: 12,
    fontWeight: '600',
    flex: 1,
  },
  buttonContainer: {
    gap: 12,
    paddingHorizontal: 16,
    paddingBottom: Platform.OS === 'ios' ? 20 : 10,
    marginTop: 16,
  },
  oauthButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    height: 52,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  googleIcon: {
    width: 20,
    height: 20,
    marginRight: 12,
  },
  oauthButtonText: {
    color: '#000',
    fontSize: 16,
    fontWeight: '700',
  },
  guestButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    height: 52,
    borderRadius: 16,
  },
  guestButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  cancelButton: {
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelButtonText: {
    color: 'rgba(255,255,255,0.5)',
    fontSize: 14,
    fontWeight: '600',
  },
  disabledButton: {
    opacity: 0.5,
  },
});
